version: '3.4'

services:
  vpn: 
    build:
      context: ./dockers/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: 'Asia/Shanghai'
      VPN_AUTH: '$VPN_USERNAME;$VPN_PASSWORD'
    networks:
      - default
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: false
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - "1080:1080"
    volumes:
      - /dev/net:/dev/net:z 
      - ./vpn:/vpn

networks:
  default: